# Generated by Django 4.2.4 on 2023-08-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_time_picker_sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
